version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: start-codex/astro
    container_name: Astro
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 1194:1194/udp
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun